spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sustc
    username: sustc
    password: sustc
    hikari:
      connection-timeout: 180000
      leak-detection-threshold: 120000

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8080

logging:
  level:
    root: off
    io.sustc: debug
